name: mobile_authenticator_fido
description: "A new Flutter project for mobile authenticator using FIDO2"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  local_auth: ^2.3.0
  shared_preferences: ^2.5.3
  logger: ^2.5.0
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  get: ^4.7.2
  get_storage: ^2.1.1
  rsa_encrypt: ^2.0.0
  biometric_storage: ^5.0.1
  device_info_plus: ^11.4.0
  android_id: ^0.4.0
  pinput: ^5.0.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/


